spring:
  application:
    name: consumer
rpc:
  register:
    zookeeper:
      ip: 192.168.1.120
      port: 2181
server:
  tomcat:
    threads:
      max: 200
    accept-count: 100
#dubbo:
#  registry:
#    address: nacos://192.168.1.120:8858
#  scan:
#    base-packages: com.lab.consumer.controller
#  application:
#    name: consumer
#  protocol:
#    name: dubbo
#    port: -1
