spring:
  application:
    name: provider
server:
  port: 8088
rpc:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true