spring:
  application:
    name: provider
server:
  port: 8080
rpc:
  netty:
    server:
      port: 8090
  register:
    zookeeper:
      ip: 192.168.1.120
      port: 2181
    nacos:
      ip: 192.168.1.120
      port: 8858
      username: nacos
      password: nacos
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
#dubbo:
#  registry:
#    address: nacos://192.168.1.120:8858
#  scan:
#    base-packages: com.lab.provider.service
#  application:
#    name: provider
#  protocol:
#    name: dubbo
#    port: -1
