spring:
  application:
    name: provider
server:
  port: 8080
rpc:
  netty:
    server:
      port: 8090
  register:
    zookeeper:
      ip: 192.168.1.120
      port: 2181
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true