// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RPC_request_proto.proto
// Protobuf Java Version: 4.30.2

package com.lab.rpccommon.message.proto;

public final class RPCRequestProto {
  private RPCRequestProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      RPCRequestProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RPCRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.RPCRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string serverName = 1;</code>
     * @return The serverName.
     */
    java.lang.String getServerName();
    /**
     * <code>string serverName = 1;</code>
     * @return The bytes for serverName.
     */
    com.google.protobuf.ByteString
        getServerNameBytes();

    /**
     * <code>string functionName = 2;</code>
     * @return The functionName.
     */
    java.lang.String getFunctionName();
    /**
     * <code>string functionName = 2;</code>
     * @return The bytes for functionName.
     */
    com.google.protobuf.ByteString
        getFunctionNameBytes();

    /**
     * <code>repeated string parameter_types = 3;</code>
     * @return A list containing the parameterTypes.
     */
    java.util.List<java.lang.String>
        getParameterTypesList();
    /**
     * <code>repeated string parameter_types = 3;</code>
     * @return The count of parameterTypes.
     */
    int getParameterTypesCount();
    /**
     * <code>repeated string parameter_types = 3;</code>
     * @param index The index of the element to return.
     * @return The parameterTypes at the given index.
     */
    java.lang.String getParameterTypes(int index);
    /**
     * <code>repeated string parameter_types = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameterTypes at the given index.
     */
    com.google.protobuf.ByteString
        getParameterTypesBytes(int index);

    /**
     * <code>repeated string parameters = 4;</code>
     * @return A list containing the parameters.
     */
    java.util.List<java.lang.String>
        getParametersList();
    /**
     * <code>repeated string parameters = 4;</code>
     * @return The count of parameters.
     */
    int getParametersCount();
    /**
     * <code>repeated string parameters = 4;</code>
     * @param index The index of the element to return.
     * @return The parameters at the given index.
     */
    java.lang.String getParameters(int index);
    /**
     * <code>repeated string parameters = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameters at the given index.
     */
    com.google.protobuf.ByteString
        getParametersBytes(int index);
  }
  /**
   * Protobuf type {@code proto.RPCRequest}
   */
  public static final class RPCRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.RPCRequest)
      RPCRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        RPCRequest.class.getName());
    }
    // Use RPCRequest.newBuilder() to construct.
    private RPCRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RPCRequest() {
      serverName_ = "";
      functionName_ = "";
      parameterTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      parameters_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lab.rpccommon.message.proto.RPCRequestProto.internal_static_proto_RPCRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lab.rpccommon.message.proto.RPCRequestProto.internal_static_proto_RPCRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest.class, com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest.Builder.class);
    }

    public static final int SERVERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serverName_ = "";
    /**
     * <code>string serverName = 1;</code>
     * @return The serverName.
     */
    @java.lang.Override
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverName_ = s;
        return s;
      }
    }
    /**
     * <code>string serverName = 1;</code>
     * @return The bytes for serverName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNCTIONNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object functionName_ = "";
    /**
     * <code>string functionName = 2;</code>
     * @return The functionName.
     */
    @java.lang.Override
    public java.lang.String getFunctionName() {
      java.lang.Object ref = functionName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functionName_ = s;
        return s;
      }
    }
    /**
     * <code>string functionName = 2;</code>
     * @return The bytes for functionName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFunctionNameBytes() {
      java.lang.Object ref = functionName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETER_TYPES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList parameterTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string parameter_types = 3;</code>
     * @return A list containing the parameterTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParameterTypesList() {
      return parameterTypes_;
    }
    /**
     * <code>repeated string parameter_types = 3;</code>
     * @return The count of parameterTypes.
     */
    public int getParameterTypesCount() {
      return parameterTypes_.size();
    }
    /**
     * <code>repeated string parameter_types = 3;</code>
     * @param index The index of the element to return.
     * @return The parameterTypes at the given index.
     */
    public java.lang.String getParameterTypes(int index) {
      return parameterTypes_.get(index);
    }
    /**
     * <code>repeated string parameter_types = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameterTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParameterTypesBytes(int index) {
      return parameterTypes_.getByteString(index);
    }

    public static final int PARAMETERS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList parameters_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string parameters = 4;</code>
     * @return A list containing the parameters.
     */
    public com.google.protobuf.ProtocolStringList
        getParametersList() {
      return parameters_;
    }
    /**
     * <code>repeated string parameters = 4;</code>
     * @return The count of parameters.
     */
    public int getParametersCount() {
      return parameters_.size();
    }
    /**
     * <code>repeated string parameters = 4;</code>
     * @param index The index of the element to return.
     * @return The parameters at the given index.
     */
    public java.lang.String getParameters(int index) {
      return parameters_.get(index);
    }
    /**
     * <code>repeated string parameters = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameters at the given index.
     */
    public com.google.protobuf.ByteString
        getParametersBytes(int index) {
      return parameters_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, serverName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(functionName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, functionName_);
      }
      for (int i = 0; i < parameterTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, parameterTypes_.getRaw(i));
      }
      for (int i = 0; i < parameters_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, parameters_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, serverName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(functionName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, functionName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameterTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(parameterTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParameterTypesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameters_.size(); i++) {
          dataSize += computeStringSizeNoTag(parameters_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParametersList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest)) {
        return super.equals(obj);
      }
      com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest other = (com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest) obj;

      if (!getServerName()
          .equals(other.getServerName())) return false;
      if (!getFunctionName()
          .equals(other.getFunctionName())) return false;
      if (!getParameterTypesList()
          .equals(other.getParameterTypesList())) return false;
      if (!getParametersList()
          .equals(other.getParametersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getServerName().hashCode();
      hash = (37 * hash) + FUNCTIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFunctionName().hashCode();
      if (getParameterTypesCount() > 0) {
        hash = (37 * hash) + PARAMETER_TYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParameterTypesList().hashCode();
      }
      if (getParametersCount() > 0) {
        hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + getParametersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.RPCRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.RPCRequest)
        com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lab.rpccommon.message.proto.RPCRequestProto.internal_static_proto_RPCRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lab.rpccommon.message.proto.RPCRequestProto.internal_static_proto_RPCRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest.class, com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest.Builder.class);
      }

      // Construct using com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serverName_ = "";
        functionName_ = "";
        parameterTypes_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        parameters_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lab.rpccommon.message.proto.RPCRequestProto.internal_static_proto_RPCRequest_descriptor;
      }

      @java.lang.Override
      public com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest getDefaultInstanceForType() {
        return com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest build() {
        com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest buildPartial() {
        com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest result = new com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverName_ = serverName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.functionName_ = functionName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          parameterTypes_.makeImmutable();
          result.parameterTypes_ = parameterTypes_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          parameters_.makeImmutable();
          result.parameters_ = parameters_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest) {
          return mergeFrom((com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest other) {
        if (other == com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest.getDefaultInstance()) return this;
        if (!other.getServerName().isEmpty()) {
          serverName_ = other.serverName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getFunctionName().isEmpty()) {
          functionName_ = other.functionName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.parameterTypes_.isEmpty()) {
          if (parameterTypes_.isEmpty()) {
            parameterTypes_ = other.parameterTypes_;
            bitField0_ |= 0x00000004;
          } else {
            ensureParameterTypesIsMutable();
            parameterTypes_.addAll(other.parameterTypes_);
          }
          onChanged();
        }
        if (!other.parameters_.isEmpty()) {
          if (parameters_.isEmpty()) {
            parameters_ = other.parameters_;
            bitField0_ |= 0x00000008;
          } else {
            ensureParametersIsMutable();
            parameters_.addAll(other.parameters_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                serverName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                functionName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureParameterTypesIsMutable();
                parameterTypes_.add(s);
                break;
              } // case 26
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureParametersIsMutable();
                parameters_.add(s);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object serverName_ = "";
      /**
       * <code>string serverName = 1;</code>
       * @return The serverName.
       */
      public java.lang.String getServerName() {
        java.lang.Object ref = serverName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serverName = 1;</code>
       * @return The bytes for serverName.
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        java.lang.Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverName = 1;</code>
       * @param value The serverName to set.
       * @return This builder for chaining.
       */
      public Builder setServerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serverName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string serverName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerName() {
        serverName_ = getDefaultInstance().getServerName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string serverName = 1;</code>
       * @param value The bytes for serverName to set.
       * @return This builder for chaining.
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serverName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object functionName_ = "";
      /**
       * <code>string functionName = 2;</code>
       * @return The functionName.
       */
      public java.lang.String getFunctionName() {
        java.lang.Object ref = functionName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          functionName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string functionName = 2;</code>
       * @return The bytes for functionName.
       */
      public com.google.protobuf.ByteString
          getFunctionNameBytes() {
        java.lang.Object ref = functionName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          functionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string functionName = 2;</code>
       * @param value The functionName to set.
       * @return This builder for chaining.
       */
      public Builder setFunctionName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        functionName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string functionName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFunctionName() {
        functionName_ = getDefaultInstance().getFunctionName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string functionName = 2;</code>
       * @param value The bytes for functionName to set.
       * @return This builder for chaining.
       */
      public Builder setFunctionNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        functionName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList parameterTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureParameterTypesIsMutable() {
        if (!parameterTypes_.isModifiable()) {
          parameterTypes_ = new com.google.protobuf.LazyStringArrayList(parameterTypes_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated string parameter_types = 3;</code>
       * @return A list containing the parameterTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getParameterTypesList() {
        parameterTypes_.makeImmutable();
        return parameterTypes_;
      }
      /**
       * <code>repeated string parameter_types = 3;</code>
       * @return The count of parameterTypes.
       */
      public int getParameterTypesCount() {
        return parameterTypes_.size();
      }
      /**
       * <code>repeated string parameter_types = 3;</code>
       * @param index The index of the element to return.
       * @return The parameterTypes at the given index.
       */
      public java.lang.String getParameterTypes(int index) {
        return parameterTypes_.get(index);
      }
      /**
       * <code>repeated string parameter_types = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the parameterTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getParameterTypesBytes(int index) {
        return parameterTypes_.getByteString(index);
      }
      /**
       * <code>repeated string parameter_types = 3;</code>
       * @param index The index to set the value at.
       * @param value The parameterTypes to set.
       * @return This builder for chaining.
       */
      public Builder setParameterTypes(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParameterTypesIsMutable();
        parameterTypes_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameter_types = 3;</code>
       * @param value The parameterTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParameterTypes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParameterTypesIsMutable();
        parameterTypes_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameter_types = 3;</code>
       * @param values The parameterTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllParameterTypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureParameterTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameterTypes_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameter_types = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParameterTypes() {
        parameterTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameter_types = 3;</code>
       * @param value The bytes of the parameterTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParameterTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureParameterTypesIsMutable();
        parameterTypes_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList parameters_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureParametersIsMutable() {
        if (!parameters_.isModifiable()) {
          parameters_ = new com.google.protobuf.LazyStringArrayList(parameters_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string parameters = 4;</code>
       * @return A list containing the parameters.
       */
      public com.google.protobuf.ProtocolStringList
          getParametersList() {
        parameters_.makeImmutable();
        return parameters_;
      }
      /**
       * <code>repeated string parameters = 4;</code>
       * @return The count of parameters.
       */
      public int getParametersCount() {
        return parameters_.size();
      }
      /**
       * <code>repeated string parameters = 4;</code>
       * @param index The index of the element to return.
       * @return The parameters at the given index.
       */
      public java.lang.String getParameters(int index) {
        return parameters_.get(index);
      }
      /**
       * <code>repeated string parameters = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the parameters at the given index.
       */
      public com.google.protobuf.ByteString
          getParametersBytes(int index) {
        return parameters_.getByteString(index);
      }
      /**
       * <code>repeated string parameters = 4;</code>
       * @param index The index to set the value at.
       * @param value The parameters to set.
       * @return This builder for chaining.
       */
      public Builder setParameters(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParametersIsMutable();
        parameters_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 4;</code>
       * @param value The parameters to add.
       * @return This builder for chaining.
       */
      public Builder addParameters(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParametersIsMutable();
        parameters_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 4;</code>
       * @param values The parameters to add.
       * @return This builder for chaining.
       */
      public Builder addAllParameters(
          java.lang.Iterable<java.lang.String> values) {
        ensureParametersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameters_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParameters() {
        parameters_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 4;</code>
       * @param value The bytes of the parameters to add.
       * @return This builder for chaining.
       */
      public Builder addParametersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureParametersIsMutable();
        parameters_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.RPCRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.RPCRequest)
    private static final com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest();
    }

    public static com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RPCRequest>
        PARSER = new com.google.protobuf.AbstractParser<RPCRequest>() {
      @java.lang.Override
      public RPCRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RPCRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RPCRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lab.rpccommon.message.proto.RPCRequestProto.RPCRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RPCRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_RPCRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027RPC_request_proto.proto\022\005proto\"c\n\nRPCR" +
      "equest\022\022\n\nserverName\030\001 \001(\t\022\024\n\014functionNa" +
      "me\030\002 \001(\t\022\027\n\017parameter_types\030\003 \003(\t\022\022\n\npar" +
      "ameters\030\004 \003(\tB!\n\037com.lab.rpccommon.messa" +
      "ge.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_RPCRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_RPCRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_RPCRequest_descriptor,
        new java.lang.String[] { "ServerName", "FunctionName", "ParameterTypes", "Parameters", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
